### ISSUE TITLE
release tarball should include paramfetch binary

### ISSUE THREAD

**Issue by laser** [filecoin-project/rust-fil-proofs-ffi#16]
Users need to be able to download the Groth parameters used when sealing, verifying, and so forth. To do this, they need `paramfetch` - a binary from the `rust-fil-proofs` repo.

To make things easy for our users, the `rust-fil-proofs-ffi` CircleCI job should be modified such that it includes `paramfetch` in the release tarball. Running `cargo install filecoin-proofs` with the appropriate version should be sufficient to get the binary installed _somewhere_. From thereon out it's just a matter of copying it into the release tarball.

**Comment by dignifiedquire** [comment]
was already done
