### ISSUE TITLE
Change response code to FCPResponse enum

### ISSUE THREAD

**Issue by vmx** [filecoin-project/rust-fil-proofs-ffi#8]
During the refactoring, the response code changed its type from an [`FCPResponseStatus` enum](https://github.com/filecoin-project/rust-fil-sector-builder/blob/394b5b1bd87efbee6489a7d22dfb3b1dba697af0/sector-builder-ffi/src/responses.rs#L13-L19) to an [`isize`](https://github.com/filecoin-project/rust-fil-proofs-ffi/blob/7f8b7ca3b4d122360c08140590606b930a016ad1/src/responses.rs#L13).

Even if it's a FFI I think it's more correct to use an enum in this case. I propose using an enum specified in a separate create, so all of Filecoins FFIs can use it.

The background for opening this issue is that I'm working on https://github.com/filecoin-project/rust-fil-proofs/issues/553 which will be implemented as a macro (https://github.com/filecoin-project/rust-fil-proofs/pull/673). I would like to have this macro work across all Filecoin FFI crates. Though this means that the response code needs to have the same type.

**Comment by vmx** [comment]
May someone from the core team comment on that one? Do you agree that it makes sense to have a unified type for response codes? If yes, feel free to fix it or leave it open and I'll tackle it the next few weeks myself. I'd like to get this fixed before working on https://github.com/filecoin-project/rust-fil-sector-builder/pull/9 again.

**Comment by laser** [comment]
@vmx 

> During the refactoring, the response code changed its type from an FCPResponseStatus enum to an isize.

My name is on the git blame here, so I'll weigh in: I don't think we should use an `isize` there. I think you are correct to use an enum. In fact, I propose that you reintroduce the `FCPResponseStatus` type (or some equivalent enum with a better name).

**Comment by schomatis** [comment]
Delayed while focusing on the cache MT effort.
